### ISSUE TITLE
이벤트 및 레스토랑 정보 더미데이터 설정

### ISSUE THREAD

**Issue by KRMKGOLD** [Team-DDG/thikira-back-end#10]
완벽하게는 안해도 됩니다
이벤트는 배너 메인 사진 가진 객체 2개
레스토랑은 별점 다르고 이름 다르게 한식, 중식, 일식에 설정해주세요

**Comment by jepangLee** [comment]
이벤트 더미 두개
업체 한식 더미 두개, 중식 더미 두개
추가하였습니다.
