### ISSUE TITLE
user/event, user/restaurant 미작동

### ISSUE THREAD

**Issue by KRMKGOLD** [Team-DDG/thikira-back-end#11]
처음에는 제 개발 문제인줄 알았는데 작동하던 user/restaurant 도 미작동하기 시작했습니다.
점심시간에 토큰 문제라고 했고, 제가 제작중인 피처는 메인이기 때문에 회원가입을 할 수 없는 상황이었습니다, 그래서 swagger에서 user/create를 통해서 유저 토큰을 받아온 후 저장했습니다.

![image](https://user-images.githubusercontent.com/37148833/84592123-2fd7b700-ae7e-11ea-88a6-44dd4ed50444.png)

그 후에 swagger에 auth로 등록을 했습니다만.

![image](https://user-images.githubusercontent.com/37148833/84592127-36662e80-ae7e-11ea-9608-c812374f47ef.png)

![image](https://user-images.githubusercontent.com/37148833/84592190-bf7d6580-ae7e-11ea-8356-7bd4ecb4f26d.png)

유저토큰으로 설정한 후에 user에서 작동해야 하는 event, restaurant에서 401이 발생하기 시작했습니다.
이부분에 대해서 수정해주세요. 이 부분 작동 확인이 안되면 다음 피쳐 개발이 지장이 있을 것 같습니다

**Comment by jepangLee** [comment]
Get user/restaurant는 잘 됩니당 허허

**Comment by jepangLee** [comment]
event api 수정했습니다.
