### ISSUE TITLE
add_parcel naming change request

### ISSUE THREAD

**Issue by kimdohun0104** [Team-DDG/thikira-back-end#8]
add_parcel이라는 네이밍 보다는 address, road_address가 더 직관적이며 의미를 가진다고 생각합니다.
그리고 안드로이드 개발자 분들은 모두 address, road_address라는 네이밍을 사용하고 있습니다.
그렇기 때문에 서버쪽에서도 바꿔주셨으면 좋겠습니다.
이에 대한 의견을 말해주세요

**Comment by jepangLee** [comment]
반영하겠읍니다

**Comment by jepangLee** [comment]
반영됬습니다 의견 감사합당
